### ISSUE TITLE
Mouse event is not fired outside an iframe

### ISSUE THREAD

**Issue by milesbr0** [Unity-Technologies/furioos-sdk-js#33]
When a user starts to drag mouse, releases it outside of the iframe, then moves the cursor back in the iframe the mouse event will be stuck on mousedown. This is a really annoying bug as in our application user can rotate objects via mouse drag. Weirdly, this bug does not occour on a Firefox browser and/or in the official furioos demos.

**Comment by K-MICK** [comment]
Hello,

The bug is fixed on our test server and will be pushed soon to production.

Regards

**Comment by peettee** [comment]
I have the same issue. Was this fixed already?

**Comment by K-MICK** [comment]
Hello

An update will be pushed next week to fix sticky key, mouse issue

**Comment by milesbr0** [comment]
Was this update pushed? The issue is still present on our side
